# Generated by Django 2.1.7 on 2019-03-23 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('brand', models.TextField(null=True, verbose_name='Brand')),
                ('color', models.TextField(null=True, verbose_name='Color')),
                ('pattern', models.TextField(
                    null=True, verbose_name='Pattern')),
                ('price', models.IntegerField(null=True,
                                              verbose_name='Price')),
                ('size', models.TextField(verbose_name='Size')),
                ('is_advertisable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClothingItemEvent',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('date',
                 models.DateTimeField(auto_now=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('image_data',
                 models.ImageField(upload_to='images/', verbose_name='Image')),
                ('clothing_item_id',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='public.ClothingItem',
                     verbose_name='Clothing Item')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('amount',
                 models.IntegerField(default=0, verbose_name='Bid Amount')),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('times_worn',
                 models.IntegerField(default=0, verbose_name='Times Worn')),
            ],
        ),
        migrations.CreateModel(
            name='OutfitItem',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('clothing_item_id',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='public.OutfitItem',
                     verbose_name='Clothing Item')),
                ('outfit_id',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='public.Outfit',
                     verbose_name='Outfit')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('user',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='bidder_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='bidders',
                to='public.Profile',
                verbose_name='Bidder'),
        ),
        migrations.AddField(
            model_name='offer',
            name='owner_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='offers',
                to='public.Profile',
                verbose_name='Offer'),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='user_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='public.Profile',
                verbose_name='Clothing Item'),
        ),
    ]
