# Generated by Django 2.1.7 on 2019-03-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='clothing_type',
            field=models.CharField(blank=True, choices=[('shirt', 'shirt'), ('pants', 'pants')], default='', max_length=255),
        ),
    ]
