# Generated by Django 2.1.7 on 2019-03-23 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_clothingitem_clothing_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingitem',
            old_name='user_id',
            new_name='profile',
        ),
    ]
