# Generated by Django 2.1.7 on 2019-03-23 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20190323_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='clothing_item_id',
            new_name='clothing_item',
        ),
    ]
