# Generated by Django 2.1.7 on 2019-03-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20190323_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_data',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
