# Generated by Django 2.1.7 on 2019-03-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_auto_20190323_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_data',
            field=models.BinaryField(verbose_name='Image'),
        ),
    ]
