# Generated by Django 2.1.7 on 2019-03-24 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_auto_20190324_0005'),
    ]

    operations = [
    ]
